---
title: "GFICF Installation"
author:
- name: Gennaro Gambardella
  affiliation: TIGEM (Telethon Institute of Genetics and Medicine) 
package: gficf
output:
  BiocStyle::html_document
vignette: |
  %\VignetteIndexEntry{GFICF Installation}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-XD8QKTWJ1D"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-XD8QKTWJ1D');
</script>

# Install Dependancies (Officially supported only Linux)

`gficf` makes use of `Rcpp`, `RcppParallel` and `RcppGSL`. So you have to carry out
a few extra steps before being able to build this package. The steps are reported below for each platform.


## Ubuntu/Debian

You need gsl dev library to successfully install RcppGSL library.
On Ubuntu/Debian systems this can be accomplished by running from terminal the command 

```bash
sudo apt-get install libgsl-dev libcurl4-openssl-dev libssl-dev libxml2-dev`
```

## Mac OS X

1.2.1 Open terminal and run `xcode-select --install` to install the command line developer tools.

1.2.1. We than need to install gsl libraries. This can be done via [Homebrew](https://brew.sh/). So, still from terminal
```bash
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
```
and than use `homebrew` to install gsl with following command
```bash
brew install gsl
```


## Windows

1.3.1 Skip this first step if you are using RStudio because it will ask you automatically. Otherwise install  [Rtools](https://cran.r-project.org/bin/windows/Rtools/) and ensure  `path\to\Rtools\bin` is on your path.   

1.3.2 [Download gsl library for Windows](https://sourceforge.net/projects/gnu-scientific-library-windows/) from sourceforge and exctract it in `C:\` or where you want.   

1.3.3 Open R/Rstudio and before to istall the package from github exec the following command in the R terminal.
```R
# Change the path if you installed gsl librarie not in the default path.
# Be sure to use the format '"path/to/gsl-xxx_mingw-xxx/gsl-xxx-static"'
# In this way " characters will be mainteined and spaces 
# in the path preserved if there are.

# For example for gsl-2.2.1 compiled with mingw-6.2.0:
Sys.setenv(GSL_LIBS = '"C:/gsl-2.2.1_mingw-6.2.0/gsl-2.2.1-static"')
```


# Install GF-ICF package

Exec in R terminal the following commands
```R
# Install required bioconductor packages
if (!requireNamespace("BiocManager", quietly = TRUE)) {
  install.packages("BiocManager")
}

BiocManager::install(setdiff(c("sva","edgeR", "fgsea"),rownames(installed.packages())),update = F)

# Install gficf from github
if(!require(devtools)){ install.packages("devtools")}
devtools::install_github("gambalab/gficf")
```
